name: Jupiter Automated Tests

on: [ push ]
#on:
#  push:
#    branches:
#      - main

permissions:
  contents: write
  pages: write
  id-token: write
  statuses: write

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run JUPITER Automated Tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Check Java version
        run: java -version
      - name: Run Automates Tests
        run: ./mvnw clean test
        continue-on-error: true
      - name: Check Allure Results Directory
        run: |
          pwd
          echo "All files in the current directory: "
          ls -la
          echo "Allure results folder: "
          ls -la target/allure-results
      - name: Store Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results
          retention-days: 1

  generate-report:
    needs: test
    runs-on: ubuntu-latest
    name: Generate Allure Report
    steps:
      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: ./allure-results

      - name: Check Allure Results Directory
        run: |
          pwd
          echo "All files in the current directory: "
          ls -la
          echo "Allure results folder: "
          ls -la ./allure-results

      - name: Get Allure History
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 0

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy Report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
